export const albums = [
  
  { artist: "Radiohead", title: "OK Computer" },
  { artist: "Pink Floyd", title: "The Dark Side of the Moon" },
  { artist: "King Crimson", title: "In the Court of the Crimson King" },
  { artist: "My Bloody Valentine", title: "Loveless" },
  { artist: "Kendrick Lamar", title: "To Pimp a Butterfly" },
  { artist: "The Beatles", title: "Abbey Road" },
  { artist: "John Coltrane", title: "A Love Supreme" },
  { artist: "Radiohead", title: "Kid A" },
  { artist: "Miles Davis", title: "Kind of Blue" },
  { artist: "The Velvet Underground & Nico", title: "The Velvet Underground & Nico" },

  { artist: "Led Zeppelin", title: "Led Zeppelin IV" },
  { artist: "David Bowie", title: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars" },
  { artist: "Frank Ocean", title: "Blonde" },
  { artist: "The Strokes", title: "Is This It" },
  { artist: "Björk", title: "Homogenic" },
  { artist: "Talking Heads", title: "Remain in Light" },
  { artist: "Nas", title: "Illmatic" },
  { artist: "The Smiths", title: "The Queen Is Dead" },
  { artist: "Joy Division", title: "Unknown Pleasures" },
  { artist: "The Cure", title: "Disintegration" },

  { artist: "Chico Buarque", title: "Construção" },
  { artist: "Caetano Veloso", title: "Transa" },
  { artist: "Milton Nascimento & Lô Borges", title: "Clube da Esquina" },
  { artist: "Secos & Molhados", title: "Secos & Molhados" },
  { artist: "Tim Maia", title: "Tim Maia Racional, Vol. 1" },
  { artist: "Gilberto Gil", title: "Expresso 2222" },
  { artist: "Tom Zé", title: "Estudando o Samba" },
  { artist: "Elis Regina", title: "Elis & Tom" },
  { artist: "Os Mutantes", title: "Os Mutantes" },
  { artist: "Djavan", title: "Luz" },

  { artist: "Black Sabbath", title: "Paranoid" },
  { artist: "The Clash", title: "London Calling" },
  { artist: "Kanye West", title: "My Beautiful Dark Twisted Fantasy" },
  { artist: "Portishead", title: "Dummy" },
  { artist: "Massive Attack", title: "Mezzanine" },
  { artist: "Fleetwood Mac", title: "Rumours" },
  { artist: "Bob Dylan", title: "Highway 61 Revisited" },
  { artist: "Jeff Buckley", title: "Grace" },
  { artist: "Stevie Wonder", title: "Innervisions" },
  { artist: "Lauryn Hill", title: "The Miseducation of Lauryn Hill" },

  { artist: "Neutral Milk Hotel", title: "In the Aeroplane Over the Sea" },
  { artist: "The Beatles", title: "Revolver" },
  { artist: "The Beach Boys", title: "Pet Sounds" },
  { artist: "Can", title: "Tago Mago" },
  { artist: "Miles Davis", title: "Bitches Brew" },
  { artist: "Public Enemy", title: "It Takes a Nation of Millions to Hold Us Back" },
  { artist: "Pixies", title: "Doolittle" },
  { artist: "The Rolling Stones", title: "Exile on Main St." },
  { artist: "The Doors", title: "The Doors" },
  { artist: "Joni Mitchell", title: "Blue" },

  { artist: "OutKast", title: "Stankonia" },
  { artist: "Childish Gambino", title: "Because the Internet" },
  { artist: "FKA twigs", title: "LP1" },
  { artist: "Bon Iver", title: "For Emma, Forever Ago" },
  { artist: "Arcade Fire", title: "Funeral" },
  { artist: "Sufjan Stevens", title: "Illinois" },
  { artist: "Kendrick Lamar", title: "good kid, m.A.A.d city" },
  { artist: "A Tribe Called Quest", title: "The Low End Theory" },
  { artist: "Daft Punk", title: "Discovery" },
  { artist: "Madonna", title: "Like a Prayer" },

  { artist: "Charles Mingus", title: "Mingus Ah Um" },
  { artist: "Billie Holiday", title: "Lady in Satin" },
  { artist: "Robert Johnson", title: "King of the Delta Blues Singers" },
  { artist: "Nina Simone", title: "Pastel Blues" },

  { artist: "The Sex Pistols", title: "Never Mind the Bollocks, Here's the Sex Pistols" },
  { artist: "Nirvana", title: "Nevermind" },
  { artist: "Radiohead", title: "In Rainbows" },
  { artist: "The White Stripes", title: "Elephant" },
  { artist: "Arctic Monkeys", title: "Whatever People Say I Am, That's What I'm Not" },

  { artist: "Aphex Twin", title: "Selected Ambient Works 85-92" },
  { artist: "Boards of Canada", title: "Music Has the Right to Children" },
  { artist: "Burial", title: "Untrue" },
  { artist: "Kraftwerk", title: "Trans-Europe Express" },

  { artist: "Marvin Gaye", title: "What's Going On" },
  { artist: "Stevie Wonder", title: "Songs in the Key of Life" },
  { artist: "Aretha Franklin", title: "I Never Loved a Man the Way I Love You" },
  { artist: "Prince", title: "Purple Rain" },

  { artist: "Wu-Tang Clan", title: "Enter the Wu-Tang (36 Chambers)" },
  { artist: "Dr. Dre", title: "The Chronic" },
  { artist: "Jay-Z", title: "Reasonable Doubt" },
  { artist: "Eminem", title: "The Marshall Mathers LP" },

  { artist: "Tame Impala", title: "Currents" },
  { artist: "Vampire Weekend", title: "Modern Vampires of the City" },
  { artist: "Lorde", title: "Melodrama" },
  { artist: "The National", title: "High Violet" },

  { artist: "The War on Drugs", title: "Lost in the Dream" },
  { artist: "PJ Harvey", title: "Stories from the City, Stories from the Sea" },
  { artist: "The Killers", title: "Hot Fuss" },
  { artist: "Coldplay", title: "A Rush of Blood to the Head" },
  { artist: "Death Grips", title: "The Money Store" },
  { artist: "Grimes", title: "Art Angels" },
  { artist: "Beck", title: "Sea Change" },
  { artist: "The Smashing Pumpkins", title: "Siamese Dream" },
  { artist: "Massive Attack", title: "Blue Lines" },
  { artist: "LCD Soundsystem", title: "Sound of Silver" }
];